/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ejercer_Turno;

/**
 *
 * @author lagar
 */
public class PanelContenedor extends javax.swing.JPanel {

    /**
     * Creates new form panelContenedor
     */
    public PanelContenedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJugador1 = new javax.swing.JPanel();
        lbUsuario1 = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        panelAvatar1 = new javax.swing.JPanel();
        panelJugador2 = new javax.swing.JPanel();
        lbUsuario2 = new javax.swing.JLabel();
        lbNumero2 = new javax.swing.JLabel();
        panelAvatar2 = new javax.swing.JPanel();
        panelJugador3 = new javax.swing.JPanel();
        lbUsuario3 = new javax.swing.JLabel();
        lbNumero3 = new javax.swing.JLabel();
        panelAvatar3 = new javax.swing.JPanel();
        panelJugador4 = new javax.swing.JPanel();
        lbUsuario4 = new javax.swing.JLabel();
        lbNumero4 = new javax.swing.JLabel();
        panelAvatar4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 0, 0));

        panelJugador1.setBackground(new java.awt.Color(255, 255, 0));

        lbUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsuario1.setText("Jugador 1");

        lbNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNumero.setText("7");

        panelAvatar1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelAvatar1Layout = new javax.swing.GroupLayout(panelAvatar1);
        panelAvatar1.setLayout(panelAvatar1Layout);
        panelAvatar1Layout.setHorizontalGroup(
            panelAvatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelAvatar1Layout.setVerticalGroup(
            panelAvatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelJugador1Layout = new javax.swing.GroupLayout(panelJugador1);
        panelJugador1.setLayout(panelJugador1Layout);
        panelJugador1Layout.setHorizontalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumero)
                    .addComponent(lbUsuario1)
                    .addComponent(panelAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelJugador1Layout.setVerticalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUsuario1)
                .addGap(18, 18, 18)
                .addComponent(lbNumero)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelJugador2.setBackground(new java.awt.Color(255, 255, 0));

        lbUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsuario2.setText("Jugador 2");

        lbNumero2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNumero2.setText("7");

        panelAvatar2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelAvatar2Layout = new javax.swing.GroupLayout(panelAvatar2);
        panelAvatar2.setLayout(panelAvatar2Layout);
        panelAvatar2Layout.setHorizontalGroup(
            panelAvatar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelAvatar2Layout.setVerticalGroup(
            panelAvatar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelJugador2Layout = new javax.swing.GroupLayout(panelJugador2);
        panelJugador2.setLayout(panelJugador2Layout);
        panelJugador2Layout.setHorizontalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumero2)
                    .addComponent(lbUsuario2)
                    .addComponent(panelAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelJugador2Layout.setVerticalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUsuario2)
                .addGap(18, 18, 18)
                .addComponent(lbNumero2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelJugador3.setBackground(new java.awt.Color(255, 255, 0));

        lbUsuario3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsuario3.setText("Jugador 3");

        lbNumero3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNumero3.setText("7");

        panelAvatar3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelAvatar3Layout = new javax.swing.GroupLayout(panelAvatar3);
        panelAvatar3.setLayout(panelAvatar3Layout);
        panelAvatar3Layout.setHorizontalGroup(
            panelAvatar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelAvatar3Layout.setVerticalGroup(
            panelAvatar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelJugador3Layout = new javax.swing.GroupLayout(panelJugador3);
        panelJugador3.setLayout(panelJugador3Layout);
        panelJugador3Layout.setHorizontalGroup(
            panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumero3)
                    .addComponent(lbUsuario3)
                    .addComponent(panelAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelJugador3Layout.setVerticalGroup(
            panelJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUsuario3)
                .addGap(18, 18, 18)
                .addComponent(lbNumero3)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelJugador4.setBackground(new java.awt.Color(255, 255, 0));

        lbUsuario4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsuario4.setText("Jugador 4");

        lbNumero4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNumero4.setText("7");

        panelAvatar4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelAvatar4Layout = new javax.swing.GroupLayout(panelAvatar4);
        panelAvatar4.setLayout(panelAvatar4Layout);
        panelAvatar4Layout.setHorizontalGroup(
            panelAvatar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelAvatar4Layout.setVerticalGroup(
            panelAvatar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelJugador4Layout = new javax.swing.GroupLayout(panelJugador4);
        panelJugador4.setLayout(panelJugador4Layout);
        panelJugador4Layout.setHorizontalGroup(
            panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumero4)
                    .addComponent(lbUsuario4)
                    .addComponent(panelAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelJugador4Layout.setVerticalGroup(
            panelJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUsuario4)
                .addGap(18, 18, 18)
                .addComponent(lbNumero4)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(panelJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 642, Short.MAX_VALUE)
                .addComponent(panelJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(panelJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(panelJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(panelJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbNumero2;
    private javax.swing.JLabel lbNumero3;
    private javax.swing.JLabel lbNumero4;
    private javax.swing.JLabel lbUsuario1;
    private javax.swing.JLabel lbUsuario2;
    private javax.swing.JLabel lbUsuario3;
    private javax.swing.JLabel lbUsuario4;
    private javax.swing.JPanel panelAvatar1;
    private javax.swing.JPanel panelAvatar2;
    private javax.swing.JPanel panelAvatar3;
    private javax.swing.JPanel panelAvatar4;
    private javax.swing.JPanel panelJugador1;
    private javax.swing.JPanel panelJugador2;
    private javax.swing.JPanel panelJugador3;
    private javax.swing.JPanel panelJugador4;
    // End of variables declaration//GEN-END:variables
}
