/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Configurar_Partida.MVC;

import Configurar_Partida.Interfaces.IModeloConfigurarPartida;
import Configurar_Partida.Interfaces.ObservadorConfigurarPartida;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author cmartinez
 */
public class FrmConfigurarPartida extends javax.swing.JFrame implements ObservadorConfigurarPartida {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmConfigurarPartida.class.getName());

    private final ControlConfigurarPartida control;
    private RangeSlider rangeSlider;
    private int numeroComodines = 4;
    private int numeroCartasAccion = 4;
    private int tiempoMaximoMostrarCartas = 10;

    /**
     * Creates new form FrmConfigurarPartida
     */
    public FrmConfigurarPartida(ControlConfigurarPartida control,
            IModeloConfigurarPartida modelo) {
        initComponents();
        rangeSlider = new RangeSlider();
        pnlRangeSlider.setLayout(new java.awt.BorderLayout());
        pnlRangeSlider.add(rangeSlider, java.awt.BorderLayout.CENTER);
        pnlRangeSlider.revalidate();
        pnlRangeSlider.repaint();

        rangeSlider.addPropertyChangeListener("range", evt -> {
            lblRangoMinimo.setText("Rango mínimo: " + rangeSlider.getMinValue());
            lblRangoMaximo.setText("Rango máximo: " + rangeSlider.getMaxValue());
        });

        this.control = control;
        modelo.registrarObservador(this);
        lblNumeroCartasComodin.setText(String.valueOf(numeroComodines));
        lblNumeroCartasAccion.setText(String.valueOf(numeroCartasAccion));
        lblTiempoMostrarMano.setText(String.valueOf(tiempoMaximoMostrarCartas));
        lblSegundoMostrarMano.setText(String.valueOf(tiempoMaximoMostrarCartas));

        inicializarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloConfiguracionPartida = new javax.swing.JPanel();
        lblTituloConfigurarPartida = new javax.swing.JLabel();
        lblSubtituloConfiguracionPartida = new javax.swing.JLabel();
        pnlCartasNumericas = new javax.swing.JPanel();
        lblRangoCartasNumericas = new javax.swing.JLabel();
        lblRangoMinimo = new javax.swing.JLabel();
        lblRangoMaximo = new javax.swing.JLabel();
        pnlRangeSlider = new javax.swing.JPanel();
        pnlCartasComodines = new javax.swing.JPanel();
        lblNumeroComodines = new javax.swing.JLabel();
        lblMensajeValorPermitidoComodines = new javax.swing.JLabel();
        btnMenorComodin = new javax.swing.JButton();
        btnMayorComodin = new javax.swing.JButton();
        lblNumeroCartasComodin = new javax.swing.JLabel();
        pnlCartasAccion = new javax.swing.JPanel();
        lblNumeroAccion = new javax.swing.JLabel();
        btnMenorAccion = new javax.swing.JButton();
        lblNumeroCartasAccion = new javax.swing.JLabel();
        btnMayorAccion = new javax.swing.JButton();
        lblMensajeValorPermitidoAccion = new javax.swing.JLabel();
        pnlTiempoMaximoMostrarCartas = new javax.swing.JPanel();
        lblTiempoMaximoMostrarCartas = new javax.swing.JLabel();
        btnMenorTiempo = new javax.swing.JButton();
        lblTiempoMostrarMano = new javax.swing.JLabel();
        btnMayorTiempo = new javax.swing.JButton();
        lblMensajeTiempoPermitido = new javax.swing.JLabel();
        lblSegundoMostrarMano = new javax.swing.JLabel();
        lblSegundosMostrarMano = new javax.swing.JLabel();
        pnlConfirmarCancelar = new javax.swing.JPanel();
        btnConfirmarConfiguracion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloConfigurarPartida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloConfigurarPartida.setText("Configurar Partida");

        lblSubtituloConfiguracionPartida.setText("Define los parámetros iniciales de la partida antes de dejarla disponible para otros jugadores.");

        javax.swing.GroupLayout pnlTituloConfiguracionPartidaLayout = new javax.swing.GroupLayout(pnlTituloConfiguracionPartida);
        pnlTituloConfiguracionPartida.setLayout(pnlTituloConfiguracionPartidaLayout);
        pnlTituloConfiguracionPartidaLayout.setHorizontalGroup(
            pnlTituloConfiguracionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloConfiguracionPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloConfiguracionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloConfigurarPartida)
                    .addComponent(lblSubtituloConfiguracionPartida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloConfiguracionPartidaLayout.setVerticalGroup(
            pnlTituloConfiguracionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloConfiguracionPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloConfigurarPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtituloConfiguracionPartida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblRangoCartasNumericas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRangoCartasNumericas.setText("Rango de cartas numéricas");

        lblRangoMinimo.setText("Rango mínimo: 0");

        lblRangoMaximo.setText("Rango máximo: 9");

        pnlRangeSlider.setPreferredSize(new java.awt.Dimension(400, 45));

        javax.swing.GroupLayout pnlRangeSliderLayout = new javax.swing.GroupLayout(pnlRangeSlider);
        pnlRangeSlider.setLayout(pnlRangeSliderLayout);
        pnlRangeSliderLayout.setHorizontalGroup(
            pnlRangeSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlRangeSliderLayout.setVerticalGroup(
            pnlRangeSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCartasNumericasLayout = new javax.swing.GroupLayout(pnlCartasNumericas);
        pnlCartasNumericas.setLayout(pnlCartasNumericasLayout);
        pnlCartasNumericasLayout.setHorizontalGroup(
            pnlCartasNumericasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartasNumericasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRangoCartasNumericas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartasNumericasLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(pnlCartasNumericasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCartasNumericasLayout.createSequentialGroup()
                        .addComponent(lblRangoMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRangoMaximo))
                    .addComponent(pnlRangeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );
        pnlCartasNumericasLayout.setVerticalGroup(
            pnlCartasNumericasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartasNumericasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRangoCartasNumericas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRangeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCartasNumericasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRangoMaximo)
                    .addComponent(lblRangoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblNumeroComodines.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumeroComodines.setText("Número de comodines");

        lblMensajeValorPermitidoComodines.setText("Valor permitido 1 a 8");

        btnMenorComodin.setText("-");
        btnMenorComodin.addActionListener(this::btnMenorComodinActionPerformed);

        btnMayorComodin.setText("+");
        btnMayorComodin.addActionListener(this::btnMayorComodinActionPerformed);

        lblNumeroCartasComodin.setText("4");

        javax.swing.GroupLayout pnlCartasComodinesLayout = new javax.swing.GroupLayout(pnlCartasComodines);
        pnlCartasComodines.setLayout(pnlCartasComodinesLayout);
        pnlCartasComodinesLayout.setHorizontalGroup(
            pnlCartasComodinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartasComodinesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensajeValorPermitidoComodines)
                .addGap(42, 42, 42))
            .addGroup(pnlCartasComodinesLayout.createSequentialGroup()
                .addGroup(pnlCartasComodinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCartasComodinesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumeroComodines))
                    .addGroup(pnlCartasComodinesLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnMenorComodin)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumeroCartasComodin)
                        .addGap(18, 18, 18)
                        .addComponent(btnMayorComodin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCartasComodinesLayout.setVerticalGroup(
            pnlCartasComodinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartasComodinesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumeroComodines)
                .addGap(18, 18, 18)
                .addGroup(pnlCartasComodinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenorComodin)
                    .addComponent(btnMayorComodin)
                    .addComponent(lblNumeroCartasComodin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensajeValorPermitidoComodines)
                .addGap(15, 15, 15))
        );

        lblNumeroAccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumeroAccion.setText("Número de cartas de acción");

        btnMenorAccion.setText("-");
        btnMenorAccion.addActionListener(this::btnMenorAccionActionPerformed);

        lblNumeroCartasAccion.setText("4");

        btnMayorAccion.setText("+");
        btnMayorAccion.addActionListener(this::btnMayorAccionActionPerformed);

        lblMensajeValorPermitidoAccion.setText("Valor permitido 1 a 8");

        javax.swing.GroupLayout pnlCartasAccionLayout = new javax.swing.GroupLayout(pnlCartasAccion);
        pnlCartasAccion.setLayout(pnlCartasAccionLayout);
        pnlCartasAccionLayout.setHorizontalGroup(
            pnlCartasAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartasAccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensajeValorPermitidoAccion)
                .addGap(42, 42, 42))
            .addGroup(pnlCartasAccionLayout.createSequentialGroup()
                .addGroup(pnlCartasAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCartasAccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumeroAccion))
                    .addGroup(pnlCartasAccionLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnMenorAccion)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumeroCartasAccion)
                        .addGap(18, 18, 18)
                        .addComponent(btnMayorAccion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCartasAccionLayout.setVerticalGroup(
            pnlCartasAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartasAccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumeroAccion)
                .addGap(18, 18, 18)
                .addGroup(pnlCartasAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenorAccion)
                    .addComponent(btnMayorAccion)
                    .addComponent(lblNumeroCartasAccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensajeValorPermitidoAccion)
                .addGap(15, 15, 15))
        );

        lblTiempoMaximoMostrarCartas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTiempoMaximoMostrarCartas.setText("Tiempo máximo para mostrar cartas");

        btnMenorTiempo.setText("-");
        btnMenorTiempo.addActionListener(this::btnMenorTiempoActionPerformed);

        lblTiempoMostrarMano.setText("10");

        btnMayorTiempo.setText("+");
        btnMayorTiempo.addActionListener(this::btnMayorTiempoActionPerformed);

        lblMensajeTiempoPermitido.setText("Debe ser mayor que cero.");

        lblSegundoMostrarMano.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSegundoMostrarMano.setText("10");

        lblSegundosMostrarMano.setText("segundos");

        javax.swing.GroupLayout pnlTiempoMaximoMostrarCartasLayout = new javax.swing.GroupLayout(pnlTiempoMaximoMostrarCartas);
        pnlTiempoMaximoMostrarCartas.setLayout(pnlTiempoMaximoMostrarCartasLayout);
        pnlTiempoMaximoMostrarCartasLayout.setHorizontalGroup(
            pnlTiempoMaximoMostrarCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiempoMaximoMostrarCartasLayout.createSequentialGroup()
                .addGroup(pnlTiempoMaximoMostrarCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTiempoMaximoMostrarCartasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTiempoMaximoMostrarCartas))
                    .addGroup(pnlTiempoMaximoMostrarCartasLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblMensajeTiempoPermitido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTiempoMaximoMostrarCartasLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnMenorTiempo)
                .addGap(18, 18, 18)
                .addComponent(lblTiempoMostrarMano)
                .addGap(18, 18, 18)
                .addComponent(btnMayorTiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSegundoMostrarMano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSegundosMostrarMano)
                .addGap(52, 52, 52))
        );
        pnlTiempoMaximoMostrarCartasLayout.setVerticalGroup(
            pnlTiempoMaximoMostrarCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiempoMaximoMostrarCartasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTiempoMaximoMostrarCartas)
                .addGap(18, 18, 18)
                .addGroup(pnlTiempoMaximoMostrarCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenorTiempo)
                    .addComponent(btnMayorTiempo)
                    .addComponent(lblTiempoMostrarMano)
                    .addComponent(lblSegundoMostrarMano)
                    .addComponent(lblSegundosMostrarMano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensajeTiempoPermitido)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnConfirmarConfiguracion.setText("Guardar configuración");
        btnConfirmarConfiguracion.addActionListener(this::btnConfirmarConfiguracionActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout pnlConfirmarCancelarLayout = new javax.swing.GroupLayout(pnlConfirmarCancelar);
        pnlConfirmarCancelar.setLayout(pnlConfirmarCancelarLayout);
        pnlConfirmarCancelarLayout.setHorizontalGroup(
            pnlConfirmarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfirmarCancelarLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnConfirmarConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConfirmarCancelarLayout.setVerticalGroup(
            pnlConfirmarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfirmarCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConfirmarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarConfiguracion)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCartasAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTituloConfiguracionPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlCartasNumericas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCartasComodines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pnlTiempoMaximoMostrarCartas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConfirmarCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloConfiguracionPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCartasNumericas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCartasComodines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCartasAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTiempoMaximoMostrarCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlConfirmarCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenorComodinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorComodinActionPerformed
        if (numeroComodines > 1) {
            numeroComodines--;
            lblNumeroCartasComodin.setText(String.valueOf(numeroComodines));
        }
    }//GEN-LAST:event_btnMenorComodinActionPerformed

    private void btnMayorComodinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorComodinActionPerformed
        if (numeroComodines < 8) {
            numeroComodines++;
            lblNumeroCartasComodin.setText(String.valueOf(numeroComodines));
        }
    }//GEN-LAST:event_btnMayorComodinActionPerformed

    private void btnMenorAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorAccionActionPerformed
        if (numeroCartasAccion > 1) {
            numeroCartasAccion--;
            lblNumeroCartasAccion.setText(String.valueOf(numeroCartasAccion));
        }
    }//GEN-LAST:event_btnMenorAccionActionPerformed

    private void btnMayorAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorAccionActionPerformed
        if (numeroCartasAccion < 8) {
            numeroCartasAccion++;
            lblNumeroCartasAccion.setText(String.valueOf(numeroCartasAccion));
        }
    }//GEN-LAST:event_btnMayorAccionActionPerformed

    private void btnMenorTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorTiempoActionPerformed
        if (tiempoMaximoMostrarCartas > 1) {
            tiempoMaximoMostrarCartas--;
            lblTiempoMostrarMano.setText(String.valueOf(tiempoMaximoMostrarCartas));
            lblSegundoMostrarMano.setText(String.valueOf(tiempoMaximoMostrarCartas));
        }
    }//GEN-LAST:event_btnMenorTiempoActionPerformed

    private void btnMayorTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorTiempoActionPerformed
        tiempoMaximoMostrarCartas++;
        lblTiempoMostrarMano.setText(String.valueOf(tiempoMaximoMostrarCartas));
        lblSegundoMostrarMano.setText(String.valueOf(tiempoMaximoMostrarCartas));
    }//GEN-LAST:event_btnMayorTiempoActionPerformed

    private void btnConfirmarConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarConfiguracionActionPerformed
        btnConfirmarConfiguracion.setEnabled(false);
        btnConfirmarConfiguracion.setText("Enviando...");

        control.solicitarConfiguracion(
                rangeSlider.getMinValue(),
                rangeSlider.getMaxValue(),
                numeroComodines,
                numeroCartasAccion,
                tiempoMaximoMostrarCartas
        );
    }//GEN-LAST:event_btnConfirmarConfiguracionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    @Override
    public void notificarCambio(IModeloConfigurarPartida contexto) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            btnConfirmarConfiguracion.setEnabled(true);
            btnConfirmarConfiguracion.setText("Guardar configuración");

            if (contexto.isConfiguracionExitosa()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Partida configurada correctamente.\n"
                        + "Estado: Disponible\n"
                        + "Otros jugadores ya pueden solicitar unirse.",
                        "Configuración aceptada",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            } else if (contexto.isConfiguracionRechazada()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "No se pudo configurar la partida.\n\n"
                        + "Motivo: " + contexto.getMensajeResultado(),
                        "Configuración rechazada",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarConfiguracion;
    private javax.swing.JButton btnMayorAccion;
    private javax.swing.JButton btnMayorComodin;
    private javax.swing.JButton btnMayorTiempo;
    private javax.swing.JButton btnMenorAccion;
    private javax.swing.JButton btnMenorComodin;
    private javax.swing.JButton btnMenorTiempo;
    private javax.swing.JLabel lblMensajeTiempoPermitido;
    private javax.swing.JLabel lblMensajeValorPermitidoAccion;
    private javax.swing.JLabel lblMensajeValorPermitidoComodines;
    private javax.swing.JLabel lblNumeroAccion;
    private javax.swing.JLabel lblNumeroCartasAccion;
    private javax.swing.JLabel lblNumeroCartasComodin;
    private javax.swing.JLabel lblNumeroComodines;
    private javax.swing.JLabel lblRangoCartasNumericas;
    private javax.swing.JLabel lblRangoMaximo;
    private javax.swing.JLabel lblRangoMinimo;
    private javax.swing.JLabel lblSegundoMostrarMano;
    private javax.swing.JLabel lblSegundosMostrarMano;
    private javax.swing.JLabel lblSubtituloConfiguracionPartida;
    private javax.swing.JLabel lblTiempoMaximoMostrarCartas;
    private javax.swing.JLabel lblTiempoMostrarMano;
    private javax.swing.JLabel lblTituloConfigurarPartida;
    private javax.swing.JPanel pnlCartasAccion;
    private javax.swing.JPanel pnlCartasComodines;
    private javax.swing.JPanel pnlCartasNumericas;
    private javax.swing.JPanel pnlConfirmarCancelar;
    private javax.swing.JPanel pnlRangeSlider;
    private javax.swing.JPanel pnlTiempoMaximoMostrarCartas;
    private javax.swing.JPanel pnlTituloConfiguracionPartida;
    // End of variables declaration//GEN-END:variables

    private void inicializarVentana() {
        setTitle("UNO Spin - Configurar partida");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(560, 720);
        setLocationRelativeTo(null);
    }
}
