<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>Itson</groupId>
        <artifactId>Broker</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>BrokerApp</artifactId>
    <packaging>jar</packaging>
    <properties>
        <maven.compiler.release>25</maven.compiler.release>
        <exec.mainClass>org.broker.MainBroker</exec.mainClass>
    </properties>
    <dependencies>
        <dependency>
            <groupId>Itson</groupId>
            <artifactId>Evento</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>Itson</groupId>
            <artifactId>Code_Desc</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>Itson</groupId>
            <artifactId>ComponenteConexion</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>Itson</groupId>
            <artifactId>Directorio</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>